sudo: required
language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
matrix:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    services:
      - xvfb
  - os: linux
    dist: xenial
    r: release
    services:
      - xvfb
    r_packages:
      - covr
      - devtools
    r_github_packages:
      - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    services:
      - xvfb
    r_packages:
      - devtools
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        update: true
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
